### ISSUE TITLE
Temperatures

### ISSUE THREAD

**Issue by a13xie** [a13xie/router_prometheus#3]
### Wireless interface temperature:
 * Broadcom DD-WRT: `wl -i INTERFACE phy_tempsense`

### CPU temperature:
 * Broadcom DD-WRT: `/proc/dmu/temperature`

**Comment by k8ieone** [comment]
[Some devices](https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=37460) seem to have temperature information at `/sys/class/i2c-adapter/i2c-0/0-0028/temp_input`
